### ISSUE TITLE
Technical Suggestion

### ISSUE THREAD

**Issue by JasonWYZE** [heir03Z/OIM3690-Term-Project#2]
1. name attribute is not allowed in the meta tag
https://github.com/heir03Z/OIM3690-Term-Project/blob/3c618f245974e7352e0caf45b07818976370ed3c/index.html#L9-L12
2.  internal style must be inside of head
https://github.com/heir03Z/OIM3690-Term-Project/blob/3c618f245974e7352e0caf45b07818976370ed3c/index.html#L29-L30
3. missing alt attribute
https://github.com/heir03Z/OIM3690-Term-Project/blob/3c618f245974e7352e0caf45b07818976370ed3c/china.html#L16
https://github.com/heir03Z/OIM3690-Term-Project/blob/3c618f245974e7352e0caf45b07818976370ed3c/china.html#L30
4. I don't think label-module is a valid attribute in div
https://github.com/heir03Z/OIM3690-Term-Project/blob/3c618f245974e7352e0caf45b07818976370ed3c/china.html#L37

**Comment by heir03Z** [comment]
changed.
