### ISSUE TITLE
Content Suggestion

### ISSUE THREAD

**Issue by JasonWYZE** [heir03Z/OIM3690-Term-Project#3]
1. I like your design of the site map. I also notice that heading image change when the visitors is on different pages. Good job! However, I think you can make the ranking table in index page look much better.
2.  For the contact us page(email), I can only access it in the sitemap.  You can also either add it in the navigator bar or the bottom of each page.

**Comment by heir03Z** [comment]
Thank you for your thoughtful suggestions, I will make changes accordingly!
